### ISSUE TITLE
Exclude package data from sdist build

### ISSUE THREAD

**Issue by ajfriend** [uber/h3-py#125]
The sdist build is pretty large, with the zipped file around 17 MB. It looks like we can cut this way down by excluding things like `src/h3lib/tests` and `src/h3lib/website`. I'm not sure how to do this tho.

Currently, in `setup.py` it looks like this bit isn't actually doing anything around removing test folders/files:

```python
    packages = find_packages(
        'src',
        exclude = ["*.tests", "*.tests.*", "tests.*", "tests"],
    ),
```

I also tried the [`exclude_package_data` parameter](https://setuptools.readthedocs.io/en/latest/setuptools.html#including-data-files), but that didn't seem to work either.

```python
exclude_package_data={"": ["*.txt"]},
```

Maybe this is something specific to `scikit-build`, as we are doing `from skbuild import setup`?

**Comment by dfellis** [comment]
Don't you usually need to declare things like `**/*.tests` to remove things that are nested below the root directory of the project?

**Comment by ajfriend** [comment]
https://github.com/uber/h3-py/blob/944d917352a242206ff7f9ca80ee556d57489b52/CMakeLists.txt#L15-L17

@isaacbrodsky, would there be a way to specify this in the CMake file?

Actually, scratch that... I don't think the setup.py file even ends up looking at or running CMake, it just copies files over.

**Comment by jcfr** [comment]
Support for `include_package_data/exclude_package_data` was added in [scikit-build 0.7.0](https://scikit-build.readthedocs.io/en/latest/changes.html#scikit-build-0-7-0).

It turns that using this option expect you to also list file to install in `MANIEST.in`. You can find more details at https://scikit-build.readthedocs.io/en/latest/usage.html#setup-options

Since in your case you would like to exclude files that would otherwise be installed by CMake I suggest instead one of the following approaches:

* Exclude CMake install rule if `SKBUILD` variable is defined. This may  not be practical if install  rule lives in a python agnostic project.

* Associate component name  with  install rules and define a custom target installing specific components. This will  be available in the upcoming scikit-build release after we integrate https://github.com/scikit-build/scikit-build/pull/477

* Define `cmake_manifest_process_hook` (see https://scikit-build.readthedocs.io/en/latest/usage.html#scikit-build-options and an example in https://github.com/jupyter-xeus/xeus-python-wheel/blob/e71c2096d57cdc0e75af05a6d34e58d3b0ce9ffc/setup.py#L24-L57)

**Comment by ajfriend** [comment]
Thanks @jcfr for taking the time to look into this!

I'm trying your third suggestion, but I'm getting the error

```
.../python3.8/distutils/dist.py:274: UserWarning: Unknown distribution option: 'cmake_process_manifest_hook'
```

at https://github.com/uber/h3-py/pull/144/checks?check_run_id=786934312#step:8:369

when I run `python setup.py sdist`.

Any idea what's happening there?

I did get confused by https://github.com/scikit-build/scikit-build/pull/505 for a second, but that PR should fix the docs. :)

**Comment by ajfriend** [comment]
For reference, discussion happening here: https://github.com/scikit-build/scikit-build/issues/500
