### ISSUE TITLE
Would it be possible to let me know how to have the following cc, make, and cmake in your $PATH when installing this package, so I can pip H3

### ISSUE THREAD

**Issue by alkenani** [uber/h3-py#22]

**Comment by dfellis** [comment]
The answer to that question depends on what operating system you're running.

**Comment by dfellis** [comment]
So currently you can't, but it should be *doable*. This binding doesn't yet run integration tests on its Windows compatibility (like the core H3 C library does) and so there are no instructions in it to do so.

Looking at [the H3 C Windows docs](https://github.com/uber/h3/blob/master/dev-docs/build_windows.md) you need to have Visual Studio 2017 installed along with [CMake for Windows](https://github.com/Kitware/CMake/releases/download/v3.13.1/cmake-3.13.1-win64-x64.msi)

Then it appears the build commands are slightly different, so this repository would need to have it's [setup.py](https://github.com/uber/h3-py/blob/master/setup.py#L14) code updated to detect the operating system and run a different install command for Windows versus everything else.

It would probably be best for @TengHu to turn this (Windows support) into a task for the repo and then he (or I, or you if you're feeling adventurous) can implement that when they have time, but getting Windows integration tests would probably require @isaacbrodsky since he's at Uber and has done that before.

Sorry that that's not the answer you're looking for. You could work around this by using [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10), installing the Windows version of Ubuntu, and then simply `sudo apt install build-essential cmake` to get a working build environment there if you're in need of an immediate solution.

**Comment by SaveTheRbtz** [comment]
The underlying problem is that packaging of the h3 is very suboptimal:
https://github.com/uber/h3-py/blob/d0dcbcde4011dcd7df90226a0a1ac7768f9cea71/.install.sh#L14-L33

Internally it was utterly painful to migrate this to Blaze^WBazel.

Downloading and running `cmake` is especially weird. You may consider fixing this for example by:
* moving h3 bindings under the main h3 repo.
* using submodules/subtrees.

While here, you can also consider switching h3 bindings to use `cffi` instead of manually boilerplating most of the code.

**Comment by ajfriend** [comment]
We just released v3.6.1, which should hopefully fix these install issues. Could you please try installing with `pip install h3==3.6.1` and let us know how it works?

I'll close this for now. Please re-open if the issue persists!
