### ISSUE TITLE
Can I download a full table of H3 index and corresponding lat&long using H3 library?

### ISSUE THREAD

**Issue by amengjiao** [uber/h3-py#321]
I want to download a full table of H3 Index (resolution 11) with the corresponding lat and long of the United States by Python H3 library. I want to import the data table to my company's database and join it to our customer records.

**Comment by nrabinowitz** [comment]
We don't provide files for download. In general it is better to use the H3 library to generate the data directly from the database or from your application code. You can use `latlng_to_cell` ([link](https://h3geo.org/docs/api/indexing/)) to get the cell ID from the lat/lon. We don't make tables of cell IDs available because at resolution 11 there are hundreds of billions of cells: https://h3geo.org/docs/core-library/restable/
