### ISSUE TITLE
API with integers as parameter

### ISSUE THREAD

**Issue by numansheikh-kt** [uber/h3-py#36]
I am told (https://github.com/uber/h3/issues/204) that the Core C lib does use 64-bit ints as the data type for H3 indexes.
Wouldn't it be more appropriate to use 64bit int as the standard parameter as well as return type when identifying hexagons in Python as well instead of hexadecimal strings?
This would have made much more sense for faster comparison and database indexing. I know we can convert it but that adds extra computations every time. 
Or at least overload each function to take/return both int64 and hexadecimal strings as valid types (wherever possible).
It was suggested that either @TengHu or @karentycoon might be better resources to help here here.

**Comment by dfellis** [comment]
As mentioned in the other issue, the hexadecimal string is the more "universal" of the two, and works with all languages, so that's why that was the original representation used in all of the bindings, with the integer representation added to the performance-focused languages.

It wasn't added to Python before release because, well, Python is the slowest of all of the languages used at Uber, so focusing on performance over clarity and ease-of-use in the Python bindings seemed backwards.

It does seem perfectly reasonable to add that support, but that's why it doesn't exist right now. I'll leave that to @karentycoon on prioritization, though, since I'm no longer with Uber and just help out on this stuff in my spare time. :)

**Comment by ajfriend** [comment]
We're trying to do exactly this with the [Cython branch](https://github.com/uber/h3-py/tree/cython). When done, I'm hoping to have three interfaces:

- sets of strings
- sets of uint64s
- numpy arrays of uint64s

I'll close this in favor of #56.
