### ISSUE TITLE
pip install h3 fails for version 3.4.2 on mac os

### ISSUE THREAD

**Issue by mbhurley1958** [uber/h3-py#38]
I've tried upgrading to h3-py version 3.4.2 from 3.1.0 using "pip install h3". Installation is reported as successful, but the C compilation does not seem to execute. The installation is not creating an h3/out directory and the dylib files. 
I have been able to revert back to version 3.1.0, which successfully installs with the C libraries correctly building.
I'm running on a mac os with Mojave 10.14.3 and anaconda 1.7.2. Some system .h files on my machine needed to be modified to successfully build to protect against the newer __has_include() function in later cc compilers. With revised .h files, the resulting libraries build and run without problems for h3 3.1.0.

I also tried hiding the pip cache directory with no improvement toward getting 3.4.2 to build the libraries.

$ which cmake
/anaconda3/bin/cmake
$ which make
/usr/bin/make
$ which cc
/anaconda3/bin/cc

**Comment by karentycoon** [comment]
Thanks for reporting @mbhurley1958 ! We do receive other users having problem when using anaconda to install. We will look into this and get back to you on any findings.

**Comment by asteriske** [comment]
I was having issues with it failing to find the function `clock_gettime` when building the h3 binary on CentOS 6. It turns out that this function moved from rt into libc at some point.

The proximal workaround was to change the line in h3's CMakeLists.txt from 'set(H3_LINK_FLAGS "")' to 'set(H3_LINK_FLAGS "rt")'. 

More concretely, I added the following right after the git checkout in h3-py's .install.sh:

sed -i 's/set(H3_LINK_FLAGS "")/set(H3_LINK_FLAGS "rt")/g' CMakeLists.txt

Relative path since it just entered the directory right before.

**Comment by ajfriend** [comment]
We just released v3.6.1, which should hopefully fix these install issues. Could you please try installing with `pip install h3==3.6.1` and let us know how it works?

I'll close this for now. Please re-open if the issue persists!
