### ISSUE TITLE
TypeError : cell_to_boundary() got an unexpected keyword argument 'geo_json'

### ISSUE THREAD

**Issue by tomrussell-willdan** [uber/h3-py#380]
cell_to_boundary() not accepting direct assingment of arguement for unpacking.
![image](https://github.com/uber/h3-py/assets/94702949/722ea6b2-5838-48f3-b0c0-ceb13cbc37c9)

**Comment by ajfriend** [comment]
Could you give an example of the behavior you're expecting?

Also, this is for v3.7. You may want to try the new v4.0: `pip install h3 --pre`

**Comment by tomrussell-willdan** [comment]
when I use the function I try to pass it explicitly the assignment of a value to the geo_json argurment but it does not like when i do that.  the example is 

What I expect to do:
```python
useGeoJsonFormat = True
cell_value = '827507fffffffff'
h3.cell_to_boundary(cell_value, geo_json=useGeoJsonFormat)
```
This thows the error in the title

What I end up having to do that works and is a work around
```python
useGeoJsonFormat = True
cell_value = '827507fffffffff'
h3.cell_to_boundary(cell_value, useGeoJsonFormat)
```

**Comment by SebKp** [comment]
@tomrussell-willdan with your solution I get:
```
TypeError: cell_to_boundary() takes 1 positional argument but 2 were given
```

It seems the flag is gone, and the documentation is out of date.

**Comment by ajfriend** [comment]
You can see the Python docs for the newly-released v4 here: https://uber.github.io/h3-py/polygon_tutorial.html

In v4, an easy way to get a [`__geo_interface__`-style dictionary](https://gist.github.com/sgillies/2217756) for the cell boundary would be:

```python
d = h3.cells_to_geo(['827507fffffffff'])
```

giving:

```python
{'type': 'Polygon',
 'coordinates': (((-3.4710946837530763, 6.357653288041298),
   (-2.159048476284375, 6.645580466394947),
   (-1.9395631182409523, 8.00719366148785),
   (-3.071080368716595, 9.072581251751162),
   (-4.392258230519222, 8.74778122110663),
   (-4.572995371627281, 7.395109809160045),
   (-3.4710946837530763, 6.357653288041298)),)}
```

which you could convert to a JSON string like:

```python
import json
json.dumps(d)
```

giving:

```json
{"type": "Polygon", "coordinates": [[[-3.4710946837530763, 6.357653288041298], [-2.159048476284375, 6.645580466394947], [-1.9395631182409523, 8.00719366148785], [-3.071080368716595, 9.072581251751162], [-4.392258230519222, 8.74778122110663], [-4.572995371627281, 7.395109809160045], [-3.4710946837530763, 6.357653288041298]]]}
```

We haven't yet added it, but maybe we should consider an option to give the GeoJSON string output, in addition to the dictionary output.

(@SebKp, your solution above is close, but it results in lat/lng ordering instead of the lng/lat ordering that GeoJSON expects.)
