### ISSUE TITLE
cell from latlng bug

### ISSUE THREAD

**Issue by owen-extent** [uber/h3-py#429]
This is not new issue but this is the first time I'm reporting it. 

>>> latlng = (29.99311, -81.33093)
>>> h3.cell_to_parent(h3.latlng_to_cell(*latlng,12),3) == h3.latlng_to_cell(*latlng,3)
False

**Comment by dfellis** [comment]
https://observablehq.com/@nrabinowitz/h3-hierarchical-non-containment

**Comment by ajfriend** [comment]
Actually, I'm working on a notebook and I think I'll add this example to the h3-py docs for future reference. Let's keep this open for now.

**Comment by ajfriend** [comment]
As @dfellis was pointing out, this is not a bug. This is entirely expected behavior.

Here's a first pass at an explanation of what's going on, but which probably needs to be cleaned up a bit more:

https://gist.github.com/ajfriend/3f9eaed6be69dd71e8f32d68be30865b

<img width="1480" alt="image" src="https://github.com/user-attachments/assets/3b3a2bea-328d-425d-a00f-069aaf571d7c">

**Comment by ajfriend** [comment]
I'll close this now. @owen-extent, let me know if you have any further questions.
