### ISSUE TITLE
Versioning question

### ISSUE THREAD

**Issue by kwmsmith** [uber/h3-py#43]
Currently, the h3-python bindings version is tied to the underlying h3 version.  This makes sense from a consistency point of view.  But what if we want to fix a critical bug in the bindings themselves, or cut a new binding-only release against the same version of H3?  What version would these new bindings have?

Waiting for a new version number of h3 core may not be feasible -- especially for critical bugs that may make the bindings unusable, for example.

Are there other mechanisms by which we can release new python bindings that make it clear what version of core they're wrapping, but have the flexibility to have their own versioning?

**Comment by isaacbrodsky** [comment]
The versioning policy we adopted in the other Uber bindings ([Java](https://github.com/uber/h3-java/blob/master/docs/versioning.md), [Javascript](https://github.com/uber/h3-js/blob/master/README.md#versioning), [Go](https://github.com/uber/h3-go/blob/master/CHANGELOG.md)) is to have the major and minor version match the bound H3 library, while the patch version is independent. It looks like that text wasn't used in the changelog for this repo, but I don't believe that was intentional.

I'd suggest we update the changelog to mention the same versioning system as the other bindings.

**Comment by kwmsmith** [comment]
That seems reasonable -- I wasn't aware of the patch version being independent until now, which addresses my concern.
