### ISSUE TITLE
geo_to_h3 and h3_to_geo yields wrong result

### ISSUE THREAD

**Issue by gacafe** [uber/h3-py#50]
There is a problem still. 
Using the example, I expect h3_to_geo(geo_to_h3(lat,lon), resolution) to return the original lat,lon input, or something quite nearby... If I use the example, this is true, but if I do it in Australia, its not true -- the [-180,180] bounds are respected but the answer is shifted by 180:

Using the Python library --
```
>>> h3_address = h3.geo_to_h3(37.3615593, -122.0553238, 15)
>>> hex_center_coordinates = h3.h3_to_geo(h3_address)
>>> hex_center_coordinates
[37.36156313952111, -122.05532505846305]
>>> h3_address = h3.geo_to_h3(130.90938479800002, -12.365644588,15)
>>> hex_center_coordinates = h3.h3_to_geo(h3_address)
>>> hex_center_coordinates
[-49.09061440581596, -12.36565153299568]
```

_Originally posted by @gacafe in https://github.com/uber/h3/issues/38#issuecomment-499309633_

**Comment by nrabinowitz** [comment]
What is your expected output here? Input latitude and longitude is accepted, but output latitude is bounded to `[-90, 90]` and output longitude is bounded to `[-180, 180]`. In your example, I think you're expecting `130.90938479800002, -12.365644588,15` to be `lon, lat`, but the input order is actually `lat, lon` - reversing the coordinates gives you a very close point in the round-trip.

There may still be an issue here, as I'm not sure we deal properly with latitudes outside the `[-90, 90]` range (round trip is close, but not as close as it should be; could just be FPE). But I think the issue you see here is due to reversed input coords.

**Comment by gacafe** [comment]
Thanks for catching that! In investigating how I arrived at the issue, I was originally using h3.polyfill(geoJson, res) and geoJson formats I have always used, usually have (lon,lat) not (lat,lon) -- probs should have read that documentation more closely :(
