### ISSUE TITLE
mismatch between `hex_ring()` docstring and implentation

### ISSUE THREAD

**Issue by ajfriend** [uber/h3-py#54]
The docstring claims that `hex_ring()` falls back to a slower algorithm when a pentagon is encountered. However, the current implementation raises an exception instead:

https://github.com/uber/h3-py/blob/392fe162f47e4d2ab33f0edde4786fe017bbd966/h3/h3.py#L490-L509

Which of these do we actually want?

**Comment by dfellis** [comment]
I think I wrote that docstring before this was open sourced. That *used* to be the behavior of the `hexRing` C code, but it looks like it was changed to not have that fallback before H3 was open sourced.

**Comment by ajfriend** [comment]
Which behavior would we prefer though?

I think we can fall back to a slower algorithm, but I don't think we need to fall back to `k_ring` necessarily, which would be **really** slow. Instead, I think we can fall back to `kRingDistances`, and just filter out the hexagons to keep only those at the maximum distance.

**Comment by dfellis** [comment]
To be honest, you have more authority than I to make that judgment call, but I do think an "always works" behavior should probably be the default for Python. Perhaps adding a `use_fallback=true` optional argument to the function definition would allow the user to override that behavior if they do care about speed of the ring generation and not completeness.

The mentioning of falling back to `k_ring` is because that's literally how we originally implemented this function before we had `kRingDistances`, literally `return k_ring(h3_address, ring_size) - k_ring(h3_address, ring_size - 1)`.

**Comment by ajfriend** [comment]
I agree that "always works" is probably best for Python. I did want to put it out there to see if there were other opinions :)

I do remember seeing that set difference logic! It looks weird now because the C `kRing` is implemented using `kRingDistances`, but I guess that probably wasn't the case back then.

**Comment by ajfriend** [comment]
This is fixed with the new cython bindings: https://github.com/uber/h3-py/blob/72db3f72d291ee3099edd473de583b0d3b057cda/src/h3/_cy/cells.pyx#L122-L123
