### ISSUE TITLE
Get Travis CI working on Cython branch

### ISSUE THREAD

**Issue by ajfriend** [uber/h3-py#58]
It would be great to get Travis CI working on the Cython branch.

I took a naive stab on [ajfriend:travis](https://github.com/ajfriend/h3-py/tree/travis), but ran into some [build issues that I didn't understand](https://travis-ci.org/ajfriend/h3-py/builds/565241453).

**Comment by isaacbrodsky** [comment]
My reading of this error is that the core library was not built with `-fPIC` but the Cython shared object was. Is it possible to add `-DCMAKE_POSITION_INDEPENDENT_CODE=ON` to the CMake command line when configuring? Otherwise I'd try enabling position independent code before `add_subdirectory`.

**Comment by ajfriend** [comment]
Tried that. Got a nice, new error: https://travis-ci.org/ajfriend/h3-py/builds/569588629

But also not entirely sure I dropped the `set(CMAKE_POSITION_INDEPENDENT_CODE ON)` in the right CMake file...

**Comment by isaacbrodsky** [comment]
It looks like the issue is that the Cython library `util.cython...so` includes unresolved references to the H3 library. (Ran `nm` on the file and noted that the symbol was "U" for undefined.) After looking into that more, the error is simply that `target_link_libraries` is called on the `h3core` Cython target but not the others. Calling this on all the Cython targets causes the tests to pass. (Note that this does statically duplicate the H3 library internally across the Cython library files. Is it possible to instead add multiple files to the same Cython module to avoid that duplication?)

**Comment by ajfriend** [comment]
Closed by #61
